# Assumes that the local repo is already fetched.

inputs:
  python_version:
    description: The Python version of the build toolchain to use.
    required: true
    default: 3.11
  extras:
    description: Optional dependencies to install, in the format '[extra1,extra2]'.
    required: false
    default: '[dev,jax,mlflow,schema]'

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: pip
        cache-dependency-path: '**/pyproject.toml'
    - shell: bash
      run: |
        pip install -e proto --config-settings editable_mode=strict
        pip install -e .${{ inputs.extras }} --config-settings editable_mode=strict
        pip freeze

