inputs:
  python_version:
    description: The Python version of the build toolchain to use.
    required: true

outputs:
  value:
    description: The current version of mmm-proto-schema
    value: ${{ steps.get_version.outputs.value }}

env:
  PROTO_DIR: "proto"

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important: fetch all tags for comparison
        fetch-tags: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.USE_PYTHON_VERSION }}

    - name: Install semver
      shell: bash
      run: pip install semver

    - name: Get version
      id: get_version
      shell: bash
      run: |
        VERSION=$(python -c """
        import sys
        import tomllib

        try:
          filepath = '${{ env.PROTO_DIR }}/pyproject.toml'
          with open(filepath, 'rb') as f:
            data = tomllib.load(f)

          version = data.get('project', {}).get('version', '')
          if version:
            print(version)
          else:
            print(f'Error: Version not found in {filepath} under [project.version]', file=sys.stderr)
            sys.exit(1)
        except FileNotFoundError:
          print(f'Error: File {filepath} not found', file=sys.stderr)
          sys.exit(1)
        """ )

        if [ $? -ne 0 ]; then
          echo "Failed to get version from ${{ env.PROTO_DIR}}/pyproject.toml"
          exit 1
        fi
        echo "value=$VERSION" >> $GITHUB_OUTPUT
