name: Version Check
description: Check if meridian.__version__ was incremented vs the latest v*-tag (fork/shallow friendly).

inputs:
  python_version:
    description: The Python version of the build toolchain to use.
    required: true
    default: 3.11

outputs:
  new_version:
    description: The new version if Meridian's semver was incremented, otherwise an empty string.
    value: ${{ steps.version_check.outputs.new_version }}

runs:
  using: composite
  steps:
    # Ensure we have the repo and history. (Keeping checkout here so the action is self-contained.)
    - uses: actions/checkout@v4
      with:
        # Full history so 'git describe' works reliably
        fetch-depth: 0

    # Make sure tags are available even if the checkout was shallow (older runners) or tags were not fetched.
    - name: Ensure full git history & tags
      shell: bash
      run: |
        set -euo pipefail
        if git rev-parse --is-shallow-repository >/dev/null 2>&1 && \
           [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
          git fetch --unshallow --tags --force --prune
        else
          git fetch --tags --force --prune
        fi
        echo "Available tags:"
        git tag -l 'v*' --sort=-v:refname | head || true

    # Set up Python env + install your package (without extras) so we can read meridian.__version__
    - uses: ./.github/actions/install-meridian
      with:
        python_version: ${{ inputs.python_version }}
        extras: ''

    - name: Install semver CLI
      shell: bash
      run: pip install semver

    - id: version_check
      name: Check Version
      shell: bash
      run: |
        set -euo pipefail

        # Read the current version from the installed package
        CURRENT_VERSION=$(python3 -c "import meridian; print(meridian.__version__)")

        # Validate CURRENT_VERSION using semver (PEP 440-compatible versions like 1.2.3, 1.2.3rc1)
        if ! python3 -m semver check "$CURRENT_VERSION"; then
          echo "Error: Invalid semantic version: $CURRENT_VERSION"
          exit 1
        fi

        # Find previous v*-tag; be fork/shallow friendly by defaulting to v0.0.0
        if ! PREVIOUS_TAG=$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null); then
          echo "No v*-tags found; defaulting to v0.0.0"
          PREVIOUS_TAG="v0.0.0"
        fi
        PREVIOUS_VERSION="${PREVIOUS_TAG#v}"

        echo "CURRENT_VERSION: $CURRENT_VERSION"
        echo "PREVIOUS_TAG:    $PREVIOUS_TAG"
        echo "PREVIOUS_VERSION:$PREVIOUS_VERSION"

        # Default output (avoid unbound var issues)
        NEW_VERSION=""

        # semver compare returns:
        #  1 if v1 > v2, 0 if equal, -1 if v1 < v2
        if [[ $(python3 -m semver compare "$CURRENT_VERSION" "$PREVIOUS_VERSION") -eq 1 ]]; then
          echo "New version detected: $CURRENT_VERSION"
          NEW_VERSION="$CURRENT_VERSION"
        else
          echo "No version increment detected."
        fi

        # Expose the output for downstream jobs
        echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
