name: Version Check
description: Check if meridian.__version__ was incremented vs the latest v*-tag (fork/shallow friendly).

inputs:
  python_version:
    description: The Python version of the build toolchain to use.
    required: true
  semver_prefix:
    description: The prefix of the package version.
    required: true
  current_version:
    description: The current package version.
    required: true

outputs:
  new_version:
    description: The new version if Meridian's semver was incremented, otherwise an empty string.
    value: ${{ steps.version_check.outputs.new_version }}

runs:
  using: composite
  steps:
    # Ensure we have the repo and history. (Keeping checkout here so the action is self-contained.)
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important: fetch all tags for comparison
        fetch-tags: true
    - shell: bash
      run: pip install semver

    - id: version_check
      name: Check Version
      shell: bash
      # This relies on the git repository having "{prefix}{major}.{minor}.{patch}" named tags.
      run: |
        CURRENT_VERSION=${{ inputs.current_version }}
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 --match '${{ inputs.semver_prefix }}*' || { echo "Error: No matching previous tag found." >&2; exit 1; })
        PREVIOUS_VERSION=$(echo "$PREVIOUS_TAG" | sed 's/^${{ inputs.semver_prefix }}//')

        echo "CURRENT_VERSION: $CURRENT_VERSION"
        echo "PREVIOUS_TAG: $PREVIOUS_TAG"
        echo "PREVIOUS_VERSION: $PREVIOUS_VERSION"

        # Check if first version
        if [ -z "$PREVIOUS_TAG" ]; then
          echo "Warning: No matching previous tag found with pattern '${{ inputs.semver_prefix }}*'. Assuming first version."
          echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Validate CURRENT_VERSION using semver (PEP 440-compatible versions like 1.2.3, 1.2.3rc1)
        if ! python3 -m semver check "$CURRENT_VERSION"; then
          echo "Error: Invalid semantic version: $CURRENT_VERSION"
          exit 1
        fi

        if [[ $(python3 -m semver compare "$CURRENT_VERSION" "$PREVIOUS_VERSION") -eq 1 ]]; then
          echo "New version detected: $CURRENT_VERSION"
          echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        else
          echo "No version increment detected."
          echo "new_version=" >> $GITHUB_OUTPUT
        fi
